name: Test with VPN and allure

on:
  workflow_dispatch:  # Can be started manually
  pull_request:
    branches:
      - main

jobs:
  vpn_and_tests:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Install and configure VPN
      - name: Install WireGuard and resolvconf
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard resolvconf  # Install both WireGuard and resolvconf

      - name: Setup WireGuard Configuration
        run: echo "${{ secrets.VPN_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null  # Loading the configuration to the desired location

      - name: Connect to VPN
        run: |
          sudo wg-quick up wg0  # Connect to VPN
          sleep 5  # Waiting for the VPN to connect

      - name: Verify VPN Connection
        run: curl -s https://ipinfo.io  # Checking the external IP address to make sure the VPN is working

      # Step 2: Setting up and running tests
      - name: Checkout repository
        uses: actions/checkout@v4  # Cloning the repository

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"  # set up the Python version

      - name: Install requirements
        run: |
          pip install -r requirements.txt  # Installing dependencies

      - name: Install Playwright Browsers
        run: |
          playwright install  # Installing browsers for Playwright

      - name: Run tests with Xvfb
        run: xvfb-run pytest  # Running tests via Xvfb

      - name: Get allure history
        uses: actions/checkout@v4
        if: always()
        with:
          ref: gh-pages
          path: gh-pages  # Getting the report history

      - name: Allure report
        uses: simple-elf/allure-report-action@v1.6
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Publish allure
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
